services:
  db:
    image: mysql:8.0
    container_name: lms-db
    restart: always
    environment:
      MYSQL_DATABASE: lms_backend_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lms-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: lms-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/lms_backend_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8082:8080"
    networks:
      - lms-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: lms-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - lms-net

volumes:
  db_data:

networks:
  lms-net:
    driver: bridge
